name = "collaborator"
compatibility_date = "2024-01-01"

main = "src/messages.mjs"

routes = [
	{ pattern = "collaborate.metaomsorg.com", custom_domain = true }
]


[placement]
mode = "smart"

[[r2_buckets]]
binding = 'COLLABORATOR' # <~ valid JavaScript variable name
bucket_name = 'collaborator'
preview_bucket_name = "collaborator-dev"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" },
]

[[rules]]
type = "Data"
globs = ["**/*.html", "**/*.js", "**/*.css"]
fallthrough = false

# Indicate that you want the Room class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]
